version: '3.8'

services:
  cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - app

volumes:
  cache:
    driver: local

networks:
  app:
    driver: bridge