spring:
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
  graphql:
    graphiql:
      enabled: true
      path: "/api/graphql"
  cache:
    type: redis